---
- name: Deploying with Kubernetes
  hosts: localhost
  connection: local
  tasks:
    # 1. Create Namespace (The Foundation)
    - name: Create Namespace
      kubernetes.core.k8s:
        validate_certs: false
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: mern-app

    # 2. Create Configs & Secrets (The Dependencies)
    - name: Apply Secrets
      kubernetes.core.k8s:
        validate_certs: false
        state: present
        definition: "{{ lookup('file', './k8/mern-backend-secret.yaml') | from_yaml }}"

    - name: Create Config Map
      kubernetes.core.k8s:
        validate_certs: false
        state: present
        definition: "{{ lookup('file', './k8/frontend-configmap.yaml') | from_yaml }}"

    # 3. Create Services (To provide stable IPs)
    - name: Create Backend Service
      kubernetes.core.k8s:
        validate_certs: false
        state: present
        definition: "{{ lookup('file', './k8/backend-service.yaml') | from_yaml }}"

    - name: Create Frontend Service
      kubernetes.core.k8s:
        validate_certs: false
        state: present
        definition: "{{ lookup('file', './k8/frontend-service.yaml') | from_yaml }}"

    # 4. Create Deployments (The actual Pods)
    - name: Create Backend Deployment
      kubernetes.core.k8s:
        validate_certs: false
        state: present
        definition: "{{ lookup('file', './k8/backend-deployment.yaml') | from_yaml }}"

    - name: Create Frontend Deployment
      kubernetes.core.k8s:
        validate_certs: false
        state: present
        definition: "{{ lookup('file', './k8/frontend-deployment.yaml') | from_yaml }}"

    # 5. Create Ingress (The Entry Point)
    - name: Create Ingress
      kubernetes.core.k8s:
        validate_certs: false
        state: present
        definition: "{{ lookup('file', './k8/mern-ingress.yaml') | from_yaml }}"